apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nkp-cluster-visualizer-role
  labels:
    app: nkp-cluster-visualizer
    environment: production
    platform: nutanix
    version: v3.3.0
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - services
  - namespaces
  - persistentvolumeclaims
  - persistentvolumes
  - configmaps
  - secrets
  - serviceaccounts
  - endpoints
  - limitranges
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  - volumesnapshotcontents
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ndk.nutanix.com
  resources:
  - applications
  - applicationsnapshots
  - protectionplans
  - storageclusters
  - appprotectionplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataservices.nutanix.com
  resources:
  - applications
  - applicationsnapshots
  - protectionplans
  - appprotectionplans
  verbs:
  - get
  - list
  - watch
