---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nkp-cluster-visualizer-github-config
  namespace: default
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
data:
  BIND_PORT: "9090"
  CLUSTER_NAME: "nkp-dev01"
  ENABLE_DRILL_DOWN: "true"
  LOG_LEVEL: "INFO"
  REFRESH_INTERVAL: "30"
  SHOW_RESOURCE_USAGE: "true"
  THEME: "nutanix"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nkp-cluster-visualizer-github-sa
  namespace: default
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nkp-cluster-visualizer-github-role
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "namespaces"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nkp-cluster-visualizer-github-binding
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
subjects:
- kind: ServiceAccount
  name: nkp-cluster-visualizer-github-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: nkp-cluster-visualizer-github-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkp-cluster-visualizer-github
  namespace: default
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkp-cluster-visualizer-github
  template:
    metadata:
      labels:
        app: nkp-cluster-visualizer-github
        environment: test
        platform: nutanix
    spec:
      serviceAccountName: nkp-cluster-visualizer-github-sa
      initContainers:
      - name: setup-app
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Setting up NKP Cluster Visualizer from source..."
          apk add --no-cache rsync
          
          # Copy application source to app volume
          rsync -av /app-source/ /app/
          
          echo "Application source copied successfully!"
          ls -la /app/
        volumeMounts:
        - name: app-volume
          mountPath: /app
        - name: app-source
          mountPath: /app-source
      containers:
      - name: nkp-cluster-visualizer-github
        image: python:3.11-slim
        ports:
        - containerPort: 9090
          name: http
        env:
        - name: BIND_PORT
          valueFrom:
            configMapKeyRef:
              name: nkp-cluster-visualizer-github-config
              key: BIND_PORT
        - name: REFRESH_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: nkp-cluster-visualizer-github-config
              key: REFRESH_INTERVAL
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: nkp-cluster-visualizer-github-config
              key: CLUSTER_NAME
        command: ["/bin/bash", "-c"]
        args:
        - |
          cd /app
          echo "Installing dependencies from requirements.txt..."
          pip install --no-cache-dir -r requirements.txt
          echo "Starting NKP Cluster Visualizer from source..."
          python3 cluster_api.py
        volumeMounts:
        - name: app-volume
          mountPath: /app
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: app-volume
        emptyDir: {}
      - name: app-source
        hostPath:
          path: /home/nutanix/nkp-cluster-visualizer-app
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: nkp-cluster-visualizer-github-service
  namespace: default
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
spec:
  selector:
    app: nkp-cluster-visualizer-github
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nkp-cluster-visualizer-github-loadbalancer
  namespace: default
  labels:
    app: nkp-cluster-visualizer-github
    environment: test
    platform: nutanix
spec:
  selector:
    app: nkp-cluster-visualizer-github
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  type: LoadBalancer