apiVersion: v1
kind: ServiceAccount
metadata:
  name: nkp-cluster-visualizer-sa
  namespace: default
  labels:
    app: nkp-cluster-visualizer
    environment: production
    platform: nutanix
    version: v3.3.0
