apiVersion: v1
kind: Service
metadata:
  name: nkp-cluster-visualizer-service
  namespace: default
  labels:
    app: nkp-cluster-visualizer
    environment: production
    platform: nutanix
    version: v3.3.0
spec:
  type: ClusterIP
  selector:
    app: nkp-cluster-visualizer
    version: v3.0.0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
